// ARRAY FOR ENUM TYPES
const TYPE_OF_MOVEMENT_INCOME = 'Income';
const TYPE_OF_MOVEMENT_EXPENSE = 'Expense';
export const TYPE_OF_MOVEMENT_ENUM = [
  TYPE_OF_MOVEMENT_INCOME,
  TYPE_OF_MOVEMENT_EXPENSE,
];
