// ARRAY FOR ENUM TYPES
const TYPE_OF_TRANSACTION_INCOME = 'Income'
const TYPE_OF_TRANSACTION_EXPENSE = 'Expense'
export const TYPE_OF_TRANSACTION_ENUM = [
  TYPE_OF_TRANSACTION_INCOME,
  TYPE_OF_TRANSACTION_EXPENSE
]
